name: Build and Deploy

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ensai-2026
  REGION: europe-west1
  SERVICE_NAME: gender-prediction-api-2451
  IMAGE: europe-west1-docker.pkg.dev/ensai-2026/id2551/prenoms-api2451

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_JSON_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE }}

  deploy:
  runs-on: ubuntu-latest

  needs: build_and_push

  steps:
      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated
